//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xrm.Framework.CI.Common.Entities
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GetSIPackageStatus")]
	public partial class msdyn_GetSIPackageStatusRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public msdyn_GetSIPackageStatusRequest()
		{
			this.RequestName = "msdyn_GetSIPackageStatus";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GetSIPackageStatus")]
	public partial class msdyn_GetSIPackageStatusResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_GetSIPackageStatusResponse()
		{
		}
		
		public string SIPackageStatus
		{
			get
			{
				if (this.Results.Contains("SIPackageStatus"))
				{
					return ((string)(this.Results["SIPackageStatus"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GDPROptoutContact")]
	public partial class msdyn_GDPROptoutContactRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public bool optout
		{
			get
			{
				if (this.Parameters.Contains("optout"))
				{
					return ((bool)(this.Parameters["optout"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["optout"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public msdyn_GDPROptoutContactRequest()
		{
			this.RequestName = "msdyn_GDPROptoutContact";
			this.optout = default(bool);
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GDPROptoutContact")]
	public partial class msdyn_GDPROptoutContactResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_GDPROptoutContactResponse()
		{
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GDPROptoutLead")]
	public partial class msdyn_GDPROptoutLeadRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public bool optout
		{
			get
			{
				if (this.Parameters.Contains("optout"))
				{
					return ((bool)(this.Parameters["optout"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["optout"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public msdyn_GDPROptoutLeadRequest()
		{
			this.RequestName = "msdyn_GDPROptoutLead";
			this.optout = default(bool);
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GDPROptoutLead")]
	public partial class msdyn_GDPROptoutLeadResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_GDPROptoutLeadResponse()
		{
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GDPROptoutUser")]
	public partial class msdyn_GDPROptoutUserRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public bool optout
		{
			get
			{
				if (this.Parameters.Contains("optout"))
				{
					return ((bool)(this.Parameters["optout"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["optout"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public msdyn_GDPROptoutUserRequest()
		{
			this.RequestName = "msdyn_GDPROptoutUser";
			this.optout = default(bool);
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GDPROptoutUser")]
	public partial class msdyn_GDPROptoutUserResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_GDPROptoutUserResponse()
		{
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GetLegalAcceptanceStatus")]
	public partial class msdyn_GetLegalAcceptanceStatusRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public msdyn_GetLegalAcceptanceStatusRequest()
		{
			this.RequestName = "msdyn_GetLegalAcceptanceStatus";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GetLegalAcceptanceStatus")]
	public partial class msdyn_GetLegalAcceptanceStatusResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_GetLegalAcceptanceStatusResponse()
		{
		}
		
		public bool Status
		{
			get
			{
				if (this.Results.Contains("Status"))
				{
					return ((bool)(this.Results["Status"]));
				}
				else
				{
					return default(bool);
				}
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_SetLegalAcceptanceStatus")]
	public partial class msdyn_SetLegalAcceptanceStatusRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public bool Status
		{
			get
			{
				if (this.Parameters.Contains("Status"))
				{
					return ((bool)(this.Parameters["Status"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["Status"] = value;
			}
		}
		
		public msdyn_SetLegalAcceptanceStatusRequest()
		{
			this.RequestName = "msdyn_SetLegalAcceptanceStatus";
			this.Status = default(bool);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_SetLegalAcceptanceStatus")]
	public partial class msdyn_SetLegalAcceptanceStatusResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_SetLegalAcceptanceStatusResponse()
		{
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("deac_ReplyCabinetMessage")]
	public partial class deac_ReplyCabinetMessageRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public deac_ReplyCabinetMessageRequest()
		{
			this.RequestName = "deac_ReplyCabinetMessage";
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("deac_ReplyCabinetMessage")]
	public partial class deac_ReplyCabinetMessageResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public deac_ReplyCabinetMessageResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.EntityReference NewActivity
		{
			get
			{
				if (this.Results.Contains("NewActivity"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Results["NewActivity"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("deac_GetNextCableName")]
	public partial class deac_GetNextCableNameRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public int CableStructure
		{
			get
			{
				if (this.Parameters.Contains("CableStructure"))
				{
					return ((int)(this.Parameters["CableStructure"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["CableStructure"] = value;
			}
		}
		
		public deac_GetNextCableNameRequest()
		{
			this.RequestName = "deac_GetNextCableName";
			this.CableStructure = default(int);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("deac_GetNextCableName")]
	public partial class deac_GetNextCableNameResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public deac_GetNextCableNameResponse()
		{
		}
		
		public string Name
		{
			get
			{
				if (this.Results.Contains("Name"))
				{
					return ((string)(this.Results["Name"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("deac_GetSalutation")]
	public partial class deac_GetSalutationRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string firstname
		{
			get
			{
				if (this.Parameters.Contains("firstname"))
				{
					return ((string)(this.Parameters["firstname"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["firstname"] = value;
			}
		}
		
		public string new_fathersname
		{
			get
			{
				if (this.Parameters.Contains("new_fathersname"))
				{
					return ((string)(this.Parameters["new_fathersname"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["new_fathersname"] = value;
			}
		}
		
		public string lastname
		{
			get
			{
				if (this.Parameters.Contains("lastname"))
				{
					return ((string)(this.Parameters["lastname"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["lastname"] = value;
			}
		}
		
		public int language
		{
			get
			{
				if (this.Parameters.Contains("language"))
				{
					return ((int)(this.Parameters["language"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["language"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public deac_GetSalutationRequest()
		{
			this.RequestName = "deac_GetSalutation";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("deac_GetSalutation")]
	public partial class deac_GetSalutationResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public deac_GetSalutationResponse()
		{
		}
		
		public string result
		{
			get
			{
				if (this.Results.Contains("result"))
				{
					return ((string)(this.Results["result"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("deac_ReparentAdvanced")]
	public partial class deac_ReparentAdvancedRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference Revokee
		{
			get
			{
				if (this.Parameters.Contains("Revokee"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Revokee"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Revokee"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference PrincipalAccess
		{
			get
			{
				if (this.Parameters.Contains("PrincipalAccess"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["PrincipalAccess"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["PrincipalAccess"] = value;
			}
		}
		
		public deac_ReparentAdvancedRequest()
		{
			this.RequestName = "deac_ReparentAdvanced";
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("deac_ReparentAdvanced")]
	public partial class deac_ReparentAdvancedResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public deac_ReparentAdvancedResponse()
		{
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("deac_GetDefaultTeamQueue")]
	public partial class deac_GetDefaultTeamQueueRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public int RecordCreationEntity
		{
			get
			{
				if (this.Parameters.Contains("RecordCreationEntity"))
				{
					return ((int)(this.Parameters["RecordCreationEntity"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["RecordCreationEntity"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public deac_GetDefaultTeamQueueRequest()
		{
			this.RequestName = "deac_GetDefaultTeamQueue";
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("deac_GetDefaultTeamQueue")]
	public partial class deac_GetDefaultTeamQueueResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public deac_GetDefaultTeamQueueResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Queue
		{
			get
			{
				if (this.Results.Contains("Queue"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Results["Queue"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("deac_CheckTicketSendAutoresponse")]
	public partial class deac_CheckTicketSendAutoresponseRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public bool EvaluateTicketCriteria
		{
			get
			{
				if (this.Parameters.Contains("EvaluateTicketCriteria"))
				{
					return ((bool)(this.Parameters["EvaluateTicketCriteria"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["EvaluateTicketCriteria"] = value;
			}
		}
		
		public bool EvaluateLoopProtection
		{
			get
			{
				if (this.Parameters.Contains("EvaluateLoopProtection"))
				{
					return ((bool)(this.Parameters["EvaluateLoopProtection"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["EvaluateLoopProtection"] = value;
			}
		}
		
		public bool EvaluateTicketRules
		{
			get
			{
				if (this.Parameters.Contains("EvaluateTicketRules"))
				{
					return ((bool)(this.Parameters["EvaluateTicketRules"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["EvaluateTicketRules"] = value;
			}
		}
		
		public string SenderEmailAddress
		{
			get
			{
				if (this.Parameters.Contains("SenderEmailAddress"))
				{
					return ((string)(this.Parameters["SenderEmailAddress"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["SenderEmailAddress"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public deac_CheckTicketSendAutoresponseRequest()
		{
			this.RequestName = "deac_CheckTicketSendAutoresponse";
			this.EvaluateTicketCriteria = default(bool);
			this.EvaluateLoopProtection = default(bool);
			this.EvaluateTicketRules = default(bool);
			this.SenderEmailAddress = default(string);
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("deac_CheckTicketSendAutoresponse")]
	public partial class deac_CheckTicketSendAutoresponseResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public deac_CheckTicketSendAutoresponseResponse()
		{
		}
		
		public bool SendResponse
		{
			get
			{
				if (this.Results.Contains("SendResponse"))
				{
					return ((bool)(this.Results["SendResponse"]));
				}
				else
				{
					return default(bool);
				}
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("deac_RetrieveTicketRecipients")]
	public partial class deac_RetrieveTicketRecipientsRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public deac_RetrieveTicketRecipientsRequest()
		{
			this.RequestName = "deac_RetrieveTicketRecipients";
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("deac_RetrieveTicketRecipients")]
	public partial class deac_RetrieveTicketRecipientsResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public deac_RetrieveTicketRecipientsResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection Cc
		{
			get
			{
				if (this.Results.Contains("Cc"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Results["Cc"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
		}
		
		public Microsoft.Xrm.Sdk.Entity From
		{
			get
			{
				if (this.Results.Contains("From"))
				{
					return ((Microsoft.Xrm.Sdk.Entity)(this.Results["From"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.Entity);
				}
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection To
		{
			get
			{
				if (this.Results.Contains("To"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Results["To"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("deac_CabinetSendJSONToMessageBroker")]
	public partial class deac_CabinetSendJSONToMessageBrokerRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public bool InboundStream
		{
			get
			{
				if (this.Parameters.Contains("InboundStream"))
				{
					return ((bool)(this.Parameters["InboundStream"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["InboundStream"] = value;
			}
		}
		
		public string Message
		{
			get
			{
				if (this.Parameters.Contains("Message"))
				{
					return ((string)(this.Parameters["Message"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Message"] = value;
			}
		}
		
		public deac_CabinetSendJSONToMessageBrokerRequest()
		{
			this.RequestName = "deac_CabinetSendJSONToMessageBroker";
			this.InboundStream = default(bool);
			this.Message = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("deac_CabinetSendJSONToMessageBroker")]
	public partial class deac_CabinetSendJSONToMessageBrokerResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public deac_CabinetSendJSONToMessageBrokerResponse()
		{
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("deac_TransferOutsourcedServices")]
	public partial class deac_TransferOutsourcedServicesRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference TargetServiceContract
		{
			get
			{
				if (this.Parameters.Contains("TargetServiceContract"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["TargetServiceContract"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["TargetServiceContract"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection OutsourcedServices
		{
			get
			{
				if (this.Parameters.Contains("OutsourcedServices"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Parameters["OutsourcedServices"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
			set
			{
				this.Parameters["OutsourcedServices"] = value;
			}
		}
		
		public System.DateTime StartDate
		{
			get
			{
				if (this.Parameters.Contains("StartDate"))
				{
					return ((System.DateTime)(this.Parameters["StartDate"]));
				}
				else
				{
					return default(System.DateTime);
				}
			}
			set
			{
				this.Parameters["StartDate"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public deac_TransferOutsourcedServicesRequest()
		{
			this.RequestName = "deac_TransferOutsourcedServices";
			this.TargetServiceContract = default(Microsoft.Xrm.Sdk.EntityReference);
			this.OutsourcedServices = default(Microsoft.Xrm.Sdk.EntityCollection);
			this.StartDate = default(System.DateTime);
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("deac_TransferOutsourcedServices")]
	public partial class deac_TransferOutsourcedServicesResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public deac_TransferOutsourcedServicesResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.EntityReference ServiceRequest
		{
			get
			{
				if (this.Results.Contains("ServiceRequest"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Results["ServiceRequest"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_RetrieveTypeValuesFromDCI")]
	public partial class msdyn_RetrieveTypeValuesFromDCIRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference CrmRecord
		{
			get
			{
				if (this.Parameters.Contains("CrmRecord"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["CrmRecord"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["CrmRecord"] = value;
			}
		}
		
		public int ResourceType
		{
			get
			{
				if (this.Parameters.Contains("ResourceType"))
				{
					return ((int)(this.Parameters["ResourceType"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["ResourceType"] = value;
			}
		}
		
		public string ResourceTypeName
		{
			get
			{
				if (this.Parameters.Contains("ResourceTypeName"))
				{
					return ((string)(this.Parameters["ResourceTypeName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ResourceTypeName"] = value;
			}
		}
		
		public System.DateTime StartDate
		{
			get
			{
				if (this.Parameters.Contains("StartDate"))
				{
					return ((System.DateTime)(this.Parameters["StartDate"]));
				}
				else
				{
					return default(System.DateTime);
				}
			}
			set
			{
				this.Parameters["StartDate"] = value;
			}
		}
		
		public System.DateTime EndDate
		{
			get
			{
				if (this.Parameters.Contains("EndDate"))
				{
					return ((System.DateTime)(this.Parameters["EndDate"]));
				}
				else
				{
					return default(System.DateTime);
				}
			}
			set
			{
				this.Parameters["EndDate"] = value;
			}
		}
		
		public msdyn_RetrieveTypeValuesFromDCIRequest()
		{
			this.RequestName = "msdyn_RetrieveTypeValuesFromDCI";
			this.CrmRecord = default(Microsoft.Xrm.Sdk.EntityReference);
			this.ResourceType = default(int);
			this.ResourceTypeName = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_RetrieveTypeValuesFromDCI")]
	public partial class msdyn_RetrieveTypeValuesFromDCIResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_RetrieveTypeValuesFromDCIResponse()
		{
		}
		
		public string ResponseValues
		{
			get
			{
				if (this.Results.Contains("ResponseValues"))
				{
					return ((string)(this.Results["ResponseValues"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("deac_GetNextSupplierServiceName")]
	public partial class deac_GetNextSupplierServiceNameRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string Category
		{
			get
			{
				if (this.Parameters.Contains("Category"))
				{
					return ((string)(this.Parameters["Category"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Category"] = value;
			}
		}
		
		public deac_GetNextSupplierServiceNameRequest()
		{
			this.RequestName = "deac_GetNextSupplierServiceName";
			this.Category = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("deac_GetNextSupplierServiceName")]
	public partial class deac_GetNextSupplierServiceNameResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public deac_GetNextSupplierServiceNameResponse()
		{
		}
		
		public string Name
		{
			get
			{
				if (this.Results.Contains("Name"))
				{
					return ((string)(this.Results["Name"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("deac_CabinetInvite")]
	public partial class deac_CabinetInviteRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public deac_CabinetInviteRequest()
		{
			this.RequestName = "deac_CabinetInvite";
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("deac_CabinetInvite")]
	public partial class deac_CabinetInviteResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public deac_CabinetInviteResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.EntityReference CabinetMessage
		{
			get
			{
				if (this.Results.Contains("CabinetMessage"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Results["CabinetMessage"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("deac_RecalculateServiceContractCurrencyBaseFields")]
	public partial class deac_RecalculateServiceContractCurrencyBaseFieldsRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public deac_RecalculateServiceContractCurrencyBaseFieldsRequest()
		{
			this.RequestName = "deac_RecalculateServiceContractCurrencyBaseFields";
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("deac_RecalculateServiceContractCurrencyBaseFields")]
	public partial class deac_RecalculateServiceContractCurrencyBaseFieldsResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public deac_RecalculateServiceContractCurrencyBaseFieldsResponse()
		{
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("deac_RunRecalculateCurrencyBaseFields")]
	public partial class deac_RunRecalculateCurrencyBaseFieldsRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public deac_RunRecalculateCurrencyBaseFieldsRequest()
		{
			this.RequestName = "deac_RunRecalculateCurrencyBaseFields";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("deac_RunRecalculateCurrencyBaseFields")]
	public partial class deac_RunRecalculateCurrencyBaseFieldsResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public deac_RunRecalculateCurrencyBaseFieldsResponse()
		{
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("deac_CreateServiceContractAnnex")]
	public partial class deac_CreateServiceContractAnnexRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference TargetServiceContract
		{
			get
			{
				if (this.Parameters.Contains("TargetServiceContract"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["TargetServiceContract"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["TargetServiceContract"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection OutsourcedServices
		{
			get
			{
				if (this.Parameters.Contains("OutsourcedServices"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Parameters["OutsourcedServices"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
			set
			{
				this.Parameters["OutsourcedServices"] = value;
			}
		}
		
		public System.DateTime StartDate
		{
			get
			{
				if (this.Parameters.Contains("StartDate"))
				{
					return ((System.DateTime)(this.Parameters["StartDate"]));
				}
				else
				{
					return default(System.DateTime);
				}
			}
			set
			{
				this.Parameters["StartDate"] = value;
			}
		}
		
		public bool CreateNewAnnex
		{
			get
			{
				if (this.Parameters.Contains("CreateNewAnnex"))
				{
					return ((bool)(this.Parameters["CreateNewAnnex"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["CreateNewAnnex"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public deac_CreateServiceContractAnnexRequest()
		{
			this.RequestName = "deac_CreateServiceContractAnnex";
			this.OutsourcedServices = default(Microsoft.Xrm.Sdk.EntityCollection);
			this.CreateNewAnnex = default(bool);
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("deac_CreateServiceContractAnnex")]
	public partial class deac_CreateServiceContractAnnexResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public deac_CreateServiceContractAnnexResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.EntityReference NewAnnex
		{
			get
			{
				if (this.Results.Contains("NewAnnex"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Results["NewAnnex"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("deac_CreateOutsourcedServiceAnnex")]
	public partial class deac_CreateOutsourcedServiceAnnexRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public deac_CreateOutsourcedServiceAnnexRequest()
		{
			this.RequestName = "deac_CreateOutsourcedServiceAnnex";
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("deac_CreateOutsourcedServiceAnnex")]
	public partial class deac_CreateOutsourcedServiceAnnexResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public deac_CreateOutsourcedServiceAnnexResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.EntityReference NewOutsourcedService
		{
			get
			{
				if (this.Results.Contains("NewOutsourcedService"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Results["NewOutsourcedService"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("deac_GetIPInfo")]
	public partial class deac_GetIPInfoRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string IP
		{
			get
			{
				if (this.Parameters.Contains("IP"))
				{
					return ((string)(this.Parameters["IP"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["IP"] = value;
			}
		}
		
		public deac_GetIPInfoRequest()
		{
			this.RequestName = "deac_GetIPInfo";
			this.IP = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("deac_GetIPInfo")]
	public partial class deac_GetIPInfoResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public deac_GetIPInfoResponse()
		{
		}
		
		public string Hex
		{
			get
			{
				if (this.Results.Contains("Hex"))
				{
					return ((string)(this.Results["Hex"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("deac_FillIpNetwork")]
	public partial class deac_FillIpNetworkRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public deac_FillIpNetworkRequest()
		{
			this.RequestName = "deac_FillIpNetwork";
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("deac_FillIpNetwork")]
	public partial class deac_FillIpNetworkResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public deac_FillIpNetworkResponse()
		{
		}
		
		public int CreatedIpCount
		{
			get
			{
				if (this.Results.Contains("CreatedIpCount"))
				{
					return ((int)(this.Results["CreatedIpCount"]));
				}
				else
				{
					return default(int);
				}
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("deac_SplitIpNetwork")]
	public partial class deac_SplitIpNetworkRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public deac_SplitIpNetworkRequest()
		{
			this.RequestName = "deac_SplitIpNetwork";
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("deac_SplitIpNetwork")]
	public partial class deac_SplitIpNetworkResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public deac_SplitIpNetworkResponse()
		{
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("deac_GetNextServiceRequestName")]
	public partial class deac_GetNextServiceRequestNameRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public deac_GetNextServiceRequestNameRequest()
		{
			this.RequestName = "deac_GetNextServiceRequestName";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("deac_GetNextServiceRequestName")]
	public partial class deac_GetNextServiceRequestNameResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public deac_GetNextServiceRequestNameResponse()
		{
		}
		
		public string Name
		{
			get
			{
				if (this.Results.Contains("Name"))
				{
					return ((string)(this.Results["Name"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("deac_DEACComposeTicketTaskDueDate")]
	public partial class deac_DEACComposeTicketTaskDueDateRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public System.DateTime lastActivity
		{
			get
			{
				if (this.Parameters.Contains("lastActivity"))
				{
					return ((System.DateTime)(this.Parameters["lastActivity"]));
				}
				else
				{
					return default(System.DateTime);
				}
			}
			set
			{
				this.Parameters["lastActivity"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public deac_DEACComposeTicketTaskDueDateRequest()
		{
			this.RequestName = "deac_DEACComposeTicketTaskDueDate";
			this.lastActivity = default(System.DateTime);
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("deac_DEACComposeTicketTaskDueDate")]
	public partial class deac_DEACComposeTicketTaskDueDateResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public deac_DEACComposeTicketTaskDueDateResponse()
		{
		}
		
		public System.DateTime dueDate
		{
			get
			{
				if (this.Results.Contains("dueDate"))
				{
					return ((System.DateTime)(this.Results["dueDate"]));
				}
				else
				{
					return default(System.DateTime);
				}
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("deac_SalesAddOutsourcedServicetoServiceRequest")]
	public partial class deac_SalesAddOutsourcedServicetoServiceRequestRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference ServiceRequest
		{
			get
			{
				if (this.Parameters.Contains("ServiceRequest"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["ServiceRequest"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["ServiceRequest"] = value;
			}
		}
		
		public int RequestType
		{
			get
			{
				if (this.Parameters.Contains("RequestType"))
				{
					return ((int)(this.Parameters["RequestType"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["RequestType"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public deac_SalesAddOutsourcedServicetoServiceRequestRequest()
		{
			this.RequestName = "deac_SalesAddOutsourcedServicetoServiceRequest";
			this.ServiceRequest = default(Microsoft.Xrm.Sdk.EntityReference);
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("deac_SalesAddOutsourcedServicetoServiceRequest")]
	public partial class deac_SalesAddOutsourcedServicetoServiceRequestResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public deac_SalesAddOutsourcedServicetoServiceRequestResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.EntityReference EntityReference
		{
			get
			{
				if (this.Results.Contains("EntityReference"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Results["EntityReference"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("deac_TranslitCyrillictoLatin")]
	public partial class deac_TranslitCyrillictoLatinRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string sourceText
		{
			get
			{
				if (this.Parameters.Contains("sourceText"))
				{
					return ((string)(this.Parameters["sourceText"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["sourceText"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public deac_TranslitCyrillictoLatinRequest()
		{
			this.RequestName = "deac_TranslitCyrillictoLatin";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("deac_TranslitCyrillictoLatin")]
	public partial class deac_TranslitCyrillictoLatinResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public deac_TranslitCyrillictoLatinResponse()
		{
		}
		
		public string translitResult
		{
			get
			{
				if (this.Results.Contains("translitResult"))
				{
					return ((string)(this.Results["translitResult"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("deac_TicketTaskButtonAction")]
	public partial class deac_TicketTaskButtonActionRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public int statuscodes
		{
			get
			{
				if (this.Parameters.Contains("statuscodes"))
				{
					return ((int)(this.Parameters["statuscodes"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["statuscodes"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public deac_TicketTaskButtonActionRequest()
		{
			this.RequestName = "deac_TicketTaskButtonAction";
			this.statuscodes = default(int);
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("deac_TicketTaskButtonAction")]
	public partial class deac_TicketTaskButtonActionResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public deac_TicketTaskButtonActionResponse()
		{
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("deac_DEACAccountingOverdueInvoicereminderforServiceContract")]
	public partial class deac_DEACAccountingOverdueInvoicereminderforServiceContractRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string notificationType
		{
			get
			{
				if (this.Parameters.Contains("notificationType"))
				{
					return ((string)(this.Parameters["notificationType"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["notificationType"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public deac_DEACAccountingOverdueInvoicereminderforServiceContractRequest()
		{
			this.RequestName = "deac_DEACAccountingOverdueInvoicereminderforServiceContract";
			this.notificationType = default(string);
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("deac_DEACAccountingOverdueInvoicereminderforServiceContract")]
	public partial class deac_DEACAccountingOverdueInvoicereminderforServiceContractResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public deac_DEACAccountingOverdueInvoicereminderforServiceContractResponse()
		{
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("deac_PrepareOverdueInvoiceNotificationCommand")]
	public partial class deac_PrepareOverdueInvoiceNotificationCommandRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityCollection selectedServiceContractReferences
		{
			get
			{
				if (this.Parameters.Contains("selectedServiceContractReferences"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Parameters["selectedServiceContractReferences"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
			set
			{
				this.Parameters["selectedServiceContractReferences"] = value;
			}
		}
		
		public string notificationType
		{
			get
			{
				if (this.Parameters.Contains("notificationType"))
				{
					return ((string)(this.Parameters["notificationType"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["notificationType"] = value;
			}
		}
		
		public deac_PrepareOverdueInvoiceNotificationCommandRequest()
		{
			this.RequestName = "deac_PrepareOverdueInvoiceNotificationCommand";
			this.selectedServiceContractReferences = default(Microsoft.Xrm.Sdk.EntityCollection);
			this.notificationType = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("deac_PrepareOverdueInvoiceNotificationCommand")]
	public partial class deac_PrepareOverdueInvoiceNotificationCommandResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public deac_PrepareOverdueInvoiceNotificationCommandResponse()
		{
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("deac_RecalculateDailyKPI")]
	public partial class deac_RecalculateDailyKPIRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public deac_RecalculateDailyKPIRequest()
		{
			this.RequestName = "deac_RecalculateDailyKPI";
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("deac_RecalculateDailyKPI")]
	public partial class deac_RecalculateDailyKPIResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public deac_RecalculateDailyKPIResponse()
		{
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("deac_DEACSalesCreateNewGoalfromexisting")]
	public partial class deac_DEACSalesCreateNewGoalfromexistingRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public deac_DEACSalesCreateNewGoalfromexistingRequest()
		{
			this.RequestName = "deac_DEACSalesCreateNewGoalfromexisting";
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("deac_DEACSalesCreateNewGoalfromexisting")]
	public partial class deac_DEACSalesCreateNewGoalfromexistingResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public deac_DEACSalesCreateNewGoalfromexistingResponse()
		{
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("deac_CalculateIRR")]
	public partial class deac_CalculateIRRRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public decimal investmentAmount
		{
			get
			{
				if (this.Parameters.Contains("investmentAmount"))
				{
					return ((decimal)(this.Parameters["investmentAmount"]));
				}
				else
				{
					return default(decimal);
				}
			}
			set
			{
				this.Parameters["investmentAmount"] = value;
			}
		}
		
		public decimal monthlyRevenue
		{
			get
			{
				if (this.Parameters.Contains("monthlyRevenue"))
				{
					return ((decimal)(this.Parameters["monthlyRevenue"]));
				}
				else
				{
					return default(decimal);
				}
			}
			set
			{
				this.Parameters["monthlyRevenue"] = value;
			}
		}
		
		public decimal months
		{
			get
			{
				if (this.Parameters.Contains("months"))
				{
					return ((decimal)(this.Parameters["months"]));
				}
				else
				{
					return default(decimal);
				}
			}
			set
			{
				this.Parameters["months"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public deac_CalculateIRRRequest()
		{
			this.RequestName = "deac_CalculateIRR";
			this.investmentAmount = default(decimal);
			this.monthlyRevenue = default(decimal);
			this.months = default(decimal);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("deac_CalculateIRR")]
	public partial class deac_CalculateIRRResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public deac_CalculateIRRResponse()
		{
		}
		
		public decimal irrValue
		{
			get
			{
				if (this.Results.Contains("irrValue"))
				{
					return ((decimal)(this.Results["irrValue"]));
				}
				else
				{
					return default(decimal);
				}
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("deac_TedGenerateTicketId")]
	public partial class deac_TedGenerateTicketIdRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public deac_TedGenerateTicketIdRequest()
		{
			this.RequestName = "deac_TedGenerateTicketId";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("deac_TedGenerateTicketId")]
	public partial class deac_TedGenerateTicketIdResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public deac_TedGenerateTicketIdResponse()
		{
		}
		
		public string generatedId
		{
			get
			{
				if (this.Results.Contains("generatedId"))
				{
					return ((string)(this.Results["generatedId"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("deac_ConvertHtmlToPlaintext")]
	public partial class deac_ConvertHtmlToPlaintextRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string HTML
		{
			get
			{
				if (this.Parameters.Contains("HTML"))
				{
					return ((string)(this.Parameters["HTML"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["HTML"] = value;
			}
		}
		
		public deac_ConvertHtmlToPlaintextRequest()
		{
			this.RequestName = "deac_ConvertHtmlToPlaintext";
			this.HTML = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("deac_ConvertHtmlToPlaintext")]
	public partial class deac_ConvertHtmlToPlaintextResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public deac_ConvertHtmlToPlaintextResponse()
		{
		}
		
		public string Plaintext
		{
			get
			{
				if (this.Results.Contains("Plaintext"))
				{
					return ((string)(this.Results["Plaintext"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("deac_RejectSIRFromSupport")]
	public partial class deac_RejectSIRFromSupportRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string RejectReason
		{
			get
			{
				if (this.Parameters.Contains("RejectReason"))
				{
					return ((string)(this.Parameters["RejectReason"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["RejectReason"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public deac_RejectSIRFromSupportRequest()
		{
			this.RequestName = "deac_RejectSIRFromSupport";
			this.RejectReason = default(string);
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("deac_RejectSIRFromSupport")]
	public partial class deac_RejectSIRFromSupportResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public deac_RejectSIRFromSupportResponse()
		{
		}
		
		public bool Error
		{
			get
			{
				if (this.Results.Contains("Error"))
				{
					return ((bool)(this.Results["Error"]));
				}
				else
				{
					return default(bool);
				}
			}
		}
		
		public string ErrorMessage
		{
			get
			{
				if (this.Results.Contains("ErrorMessage"))
				{
					return ((string)(this.Results["ErrorMessage"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("deac_FulfillSIRFromSupport")]
	public partial class deac_FulfillSIRFromSupportRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public deac_FulfillSIRFromSupportRequest()
		{
			this.RequestName = "deac_FulfillSIRFromSupport";
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("deac_FulfillSIRFromSupport")]
	public partial class deac_FulfillSIRFromSupportResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public deac_FulfillSIRFromSupportResponse()
		{
		}
		
		public bool Error
		{
			get
			{
				if (this.Results.Contains("Error"))
				{
					return ((bool)(this.Results["Error"]));
				}
				else
				{
					return default(bool);
				}
			}
		}
		
		public string ErrorMessage
		{
			get
			{
				if (this.Results.Contains("ErrorMessage"))
				{
					return ((string)(this.Results["ErrorMessage"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("deac_DEACSalesDistributeLeadtoUser")]
	public partial class deac_DEACSalesDistributeLeadtoUserRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference TargetUser
		{
			get
			{
				if (this.Parameters.Contains("TargetUser"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["TargetUser"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["TargetUser"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public deac_DEACSalesDistributeLeadtoUserRequest()
		{
			this.RequestName = "deac_DEACSalesDistributeLeadtoUser";
			this.TargetUser = default(Microsoft.Xrm.Sdk.EntityReference);
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("deac_DEACSalesDistributeLeadtoUser")]
	public partial class deac_DEACSalesDistributeLeadtoUserResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public deac_DEACSalesDistributeLeadtoUserResponse()
		{
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("deac_SalesAddAllOutsourcedServicestoServiceRequest")]
	public partial class deac_SalesAddAllOutsourcedServicestoServiceRequestRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityCollection OutsourcedServices
		{
			get
			{
				if (this.Parameters.Contains("OutsourcedServices"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Parameters["OutsourcedServices"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
			set
			{
				this.Parameters["OutsourcedServices"] = value;
			}
		}
		
		public int RequestType
		{
			get
			{
				if (this.Parameters.Contains("RequestType"))
				{
					return ((int)(this.Parameters["RequestType"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["RequestType"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public deac_SalesAddAllOutsourcedServicestoServiceRequestRequest()
		{
			this.RequestName = "deac_SalesAddAllOutsourcedServicestoServiceRequest";
			this.OutsourcedServices = default(Microsoft.Xrm.Sdk.EntityCollection);
			this.RequestType = default(int);
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("deac_SalesAddAllOutsourcedServicestoServiceRequest")]
	public partial class deac_SalesAddAllOutsourcedServicestoServiceRequestResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public deac_SalesAddAllOutsourcedServicestoServiceRequestResponse()
		{
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("deac_DEACSalesDistributeAccounttoUser")]
	public partial class deac_DEACSalesDistributeAccounttoUserRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference TargetUser
		{
			get
			{
				if (this.Parameters.Contains("TargetUser"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["TargetUser"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["TargetUser"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public deac_DEACSalesDistributeAccounttoUserRequest()
		{
			this.RequestName = "deac_DEACSalesDistributeAccounttoUser";
			this.TargetUser = default(Microsoft.Xrm.Sdk.EntityReference);
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("deac_DEACSalesDistributeAccounttoUser")]
	public partial class deac_DEACSalesDistributeAccounttoUserResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public deac_DEACSalesDistributeAccounttoUserResponse()
		{
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("deac_PickNextWorkedByForQueueItemUsingRoundRobin")]
	public partial class deac_PickNextWorkedByForQueueItemUsingRoundRobinRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference Team
		{
			get
			{
				if (this.Parameters.Contains("Team"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Team"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Team"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public deac_PickNextWorkedByForQueueItemUsingRoundRobinRequest()
		{
			this.RequestName = "deac_PickNextWorkedByForQueueItemUsingRoundRobin";
			this.Team = default(Microsoft.Xrm.Sdk.EntityReference);
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("deac_PickNextWorkedByForQueueItemUsingRoundRobin")]
	public partial class deac_PickNextWorkedByForQueueItemUsingRoundRobinResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public deac_PickNextWorkedByForQueueItemUsingRoundRobinResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.EntityReference PickedUser
		{
			get
			{
				if (this.Results.Contains("PickedUser"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Results["PickedUser"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("deac_GetNextServiceContractName")]
	public partial class deac_GetNextServiceContractNameRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public deac_GetNextServiceContractNameRequest()
		{
			this.RequestName = "deac_GetNextServiceContractName";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("deac_GetNextServiceContractName")]
	public partial class deac_GetNextServiceContractNameResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public deac_GetNextServiceContractNameResponse()
		{
		}
		
		public string Name
		{
			get
			{
				if (this.Results.Contains("Name"))
				{
					return ((string)(this.Results["Name"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("deac_SearchAccountsV2")]
	public partial class deac_SearchAccountsV2Request : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string searchTerm
		{
			get
			{
				if (this.Parameters.Contains("searchTerm"))
				{
					return ((string)(this.Parameters["searchTerm"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["searchTerm"] = value;
			}
		}
		
		public deac_SearchAccountsV2Request()
		{
			this.RequestName = "deac_SearchAccountsV2";
			this.searchTerm = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/deac/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("deac_SearchAccountsV2")]
	public partial class deac_SearchAccountsV2Response : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public deac_SearchAccountsV2Response()
		{
		}
		
		public string result
		{
			get
			{
				if (this.Results.Contains("result"))
				{
					return ((string)(this.Results["result"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GetRIProvisioningStatus")]
	public partial class msdyn_GetRIProvisioningStatusRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public msdyn_GetRIProvisioningStatusRequest()
		{
			this.RequestName = "msdyn_GetRIProvisioningStatus";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GetRIProvisioningStatus")]
	public partial class msdyn_GetRIProvisioningStatusResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_GetRIProvisioningStatusResponse()
		{
		}
		
		public string DCIHubPlanType
		{
			get
			{
				if (this.Results.Contains("DCIHubPlanType"))
				{
					return ((string)(this.Results["DCIHubPlanType"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public int EEProvisioningStatus
		{
			get
			{
				if (this.Results.Contains("EEProvisioningStatus"))
				{
					return ((int)(this.Results["EEProvisioningStatus"]));
				}
				else
				{
					return default(int);
				}
			}
		}
		
		public string RIErrorStatusCode
		{
			get
			{
				if (this.Results.Contains("RIErrorStatusCode"))
				{
					return ((string)(this.Results["RIErrorStatusCode"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string RIErrorStatusMessage
		{
			get
			{
				if (this.Results.Contains("RIErrorStatusMessage"))
				{
					return ((string)(this.Results["RIErrorStatusMessage"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public int RIProvisioningStatus
		{
			get
			{
				if (this.Results.Contains("RIProvisioningStatus"))
				{
					return ((int)(this.Results["RIProvisioningStatus"]));
				}
				else
				{
					return default(int);
				}
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_SetFeatureStatus")]
	public partial class msdyn_SetFeatureStatusRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public int FeatureType
		{
			get
			{
				if (this.Parameters.Contains("FeatureType"))
				{
					return ((int)(this.Parameters["FeatureType"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["FeatureType"] = value;
			}
		}
		
		public bool Status
		{
			get
			{
				if (this.Parameters.Contains("Status"))
				{
					return ((bool)(this.Parameters["Status"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Parameters["Status"] = value;
			}
		}
		
		public string ConfigurationData
		{
			get
			{
				if (this.Parameters.Contains("ConfigurationData"))
				{
					return ((string)(this.Parameters["ConfigurationData"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ConfigurationData"] = value;
			}
		}
		
		public msdyn_SetFeatureStatusRequest()
		{
			this.RequestName = "msdyn_SetFeatureStatus";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_SetFeatureStatus")]
	public partial class msdyn_SetFeatureStatusResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_SetFeatureStatusResponse()
		{
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GetACIMarsConnectorStatus")]
	public partial class msdyn_GetACIMarsConnectorStatusRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public msdyn_GetACIMarsConnectorStatusRequest()
		{
			this.RequestName = "msdyn_GetACIMarsConnectorStatus";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GetACIMarsConnectorStatus")]
	public partial class msdyn_GetACIMarsConnectorStatusResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_GetACIMarsConnectorStatusResponse()
		{
		}
		
		public string MarsStatus
		{
			get
			{
				if (this.Results.Contains("MarsStatus"))
				{
					return ((string)(this.Results["MarsStatus"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_StartRIProvisioning")]
	public partial class msdyn_StartRIProvisioningRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string HubName
		{
			get
			{
				if (this.Parameters.Contains("HubName"))
				{
					return ((string)(this.Parameters["HubName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["HubName"] = value;
			}
		}
		
		public string PrimaryKey
		{
			get
			{
				if (this.Parameters.Contains("PrimaryKey"))
				{
					return ((string)(this.Parameters["PrimaryKey"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["PrimaryKey"] = value;
			}
		}
		
		public msdyn_StartRIProvisioningRequest()
		{
			this.RequestName = "msdyn_StartRIProvisioning";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_StartRIProvisioning")]
	public partial class msdyn_StartRIProvisioningResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_StartRIProvisioningResponse()
		{
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_GetRITenantEndpoint")]
	public partial class msdyn_GetRITenantEndpointRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public msdyn_GetRITenantEndpointRequest()
		{
			this.RequestName = "msdyn_GetRITenantEndpoint";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_GetRITenantEndpoint")]
	public partial class msdyn_GetRITenantEndpointResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_GetRITenantEndpointResponse()
		{
		}
		
		public string TenantInfo
		{
			get
			{
				if (this.Results.Contains("TenantInfo"))
				{
					return ((string)(this.Results["TenantInfo"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_Updatefeatureconfig")]
	public partial class msdyn_UpdatefeatureconfigRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public int featureType
		{
			get
			{
				if (this.Parameters.Contains("featureType"))
				{
					return ((int)(this.Parameters["featureType"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["featureType"] = value;
			}
		}
		
		public string configuration
		{
			get
			{
				if (this.Parameters.Contains("configuration"))
				{
					return ((string)(this.Parameters["configuration"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["configuration"] = value;
			}
		}
		
		public msdyn_UpdatefeatureconfigRequest()
		{
			this.RequestName = "msdyn_Updatefeatureconfig";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_Updatefeatureconfig")]
	public partial class msdyn_UpdatefeatureconfigResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_UpdatefeatureconfigResponse()
		{
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_UpdateRITenantInfo")]
	public partial class msdyn_UpdateRITenantInfoRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string HubName
		{
			get
			{
				if (this.Parameters.Contains("HubName"))
				{
					return ((string)(this.Parameters["HubName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["HubName"] = value;
			}
		}
		
		public string PrimaryKey
		{
			get
			{
				if (this.Parameters.Contains("PrimaryKey"))
				{
					return ((string)(this.Parameters["PrimaryKey"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["PrimaryKey"] = value;
			}
		}
		
		public msdyn_UpdateRITenantInfoRequest()
		{
			this.RequestName = "msdyn_UpdateRITenantInfo";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_UpdateRITenantInfo")]
	public partial class msdyn_UpdateRITenantInfoResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_UpdateRITenantInfoResponse()
		{
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("msdyn_RetrieveKPIvaluesfromDCI")]
	public partial class msdyn_RetrieveKPIvaluesfromDCIRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public Microsoft.Xrm.Sdk.EntityReference CrmRecord
		{
			get
			{
				if (this.Parameters.Contains("CrmRecord"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["CrmRecord"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["CrmRecord"] = value;
			}
		}
		
		public string KPINameFilterMap
		{
			get
			{
				if (this.Parameters.Contains("KPINameFilterMap"))
				{
					return ((string)(this.Parameters["KPINameFilterMap"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["KPINameFilterMap"] = value;
			}
		}
		
		public msdyn_RetrieveKPIvaluesfromDCIRequest()
		{
			this.RequestName = "msdyn_RetrieveKPIvaluesfromDCI";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/msdyn/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("msdyn_RetrieveKPIvaluesfromDCI")]
	public partial class msdyn_RetrieveKPIvaluesfromDCIResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public msdyn_RetrieveKPIvaluesfromDCIResponse()
		{
		}
		
		public string Errors
		{
			get
			{
				if (this.Results.Contains("Errors"))
				{
					return ((string)(this.Results["Errors"]));
				}
				else
				{
					return default(string);
				}
			}
		}
		
		public string KPIValues
		{
			get
			{
				if (this.Results.Contains("KPIValues"))
				{
					return ((string)(this.Results["KPIValues"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/rwb/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("rwb_CustomiseRibbon")]
	public partial class rwb_CustomiseRibbonRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public string Operation
		{
			get
			{
				if (this.Parameters.Contains("Operation"))
				{
					return ((string)(this.Parameters["Operation"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Operation"] = value;
			}
		}
		
		public string Data
		{
			get
			{
				if (this.Parameters.Contains("Data"))
				{
					return ((string)(this.Parameters["Data"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Data"] = value;
			}
		}
		
		public rwb_CustomiseRibbonRequest()
		{
			this.RequestName = "rwb_CustomiseRibbon";
			this.Operation = default(string);
			this.Data = default(string);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/rwb/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("rwb_CustomiseRibbon")]
	public partial class rwb_CustomiseRibbonResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public rwb_CustomiseRibbonResponse()
		{
		}
		
		public string Result
		{
			get
			{
				if (this.Results.Contains("Result"))
				{
					return ((string)(this.Results["Result"]));
				}
				else
				{
					return default(string);
				}
			}
		}
	}
}
